### ISSUE TITLE
"Could not prepare Boot variable: Invalid argument" on lemp10

### ISSUE THREAD

**Issue by jonahweissman** [pop-os/system76-firmware#52]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
> apt policy efibootmgr 
efibootmgr:
  Installed: 17-1
  Candidate: 17-1
  Version table:
 *** 17-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

I got a notification about a firmware update. Clicking "reboot and install" failed, giving me this: `error in system76-firmware client: calling Schedule method failed: "failed to add boot entry: exit code: 5"`. I then installed the CLI, and got more detailed output: 
```
> sudo system76-firmware-cli schedule
Automatic transition: 76ec -> 76ec
downloading tail
opening download cache
downloading manifest.json
downloading system76-firmware-update.tar.xz
downloading lemp10_df60b821b2f5c45288098dba9e084aeb79d491d4133f84b73d298155aba6597e.tar.xz
loading changelog.json
Ok("./changelog.json")
Automatic transition: 76ec -> 76ec
"efibootmgr" "--quiet" "--delete-bootnext"
Could not delete BootNext: No such file or directory
"efibootmgr" "--quiet" "--delete-bootnum" "--bootnum" "1776"
Could not delete variable: No such file or directory
removing /boot/efi/system76-firmware-update
extracting system76-firmware-update.tar.xz to /boot/efi/system76-firmware-update.NNDyOTq9kGoV
Ok("./")
Ok("./boot.efi")
Ok("./res/")
Ok("./res/firmware.nsh")
Ok("./res/shell.efi")
Ok("./res/splash.bmp")
extracting lemp10_df60b821b2f5c45288098dba9e084aeb79d491d4133f84b73d298155aba6597e.tar.xz to /boot/efi/system76-firmware-update.NNDyOTq9kGoV/firmware
Ok("./")
Ok("./changelog.json")
Ok("./ec.rom")
Ok("./firmware.rom")
Ok("./fpt.efi")
Ok("./meset.efi")
Ok("./uecflash.efi")
Ok("./usb4-pd.rom")
Ok("./usb4-retimer.rom")
moving /boot/efi/system76-firmware-update.NNDyOTq9kGoV to /boot/efi/system76-firmware-update
/dev/nvme0n1 1
"efibootmgr" "--quiet" "--create-only" "--bootnum" "1776" "--disk" "/dev/nvme0n1" "--part" "1" "--loader" "\\system76-firmware-update\\boot.efi" "--label" "system76-firmware-update"
Could not prepare Boot variable: Invalid argument
system76-firmware: failed to schedule: failed to add boot entry: exit code: 5
```

**Comment by jacobgkau** [comment]
I'm sorry about the firmware updating trouble. I believe you are being impacted by this issue (which is fixed in the latest firmware version): https://github.com/system76/firmware-open/issues/145 

In order to make the update work, please try following the instructions in [this comment](https://github.com/system76/firmware-open/issues/145#issuecomment-761075957). Specifically:

- Download this file: https://github.com/system76/firmware-open/files/5822011/lemp10-76ec.zip 
- Format a USB flash drive with a single FAT32 partition (using an app like Disks or GParted)
- Extract the contents of the ZIP file onto the flash drive
- Reboot the computer

If the machine doesn't boot from the USB flash drive by default, try holding down ESC and using the boot menu to select the USB drive; if the machine doesn't respond to ESC, it may be necessary to remove all internal storage drives, leaving the USB drive as the only bootable option.

Once the system boots from the USB drive, it will automatically re-flash the current firmware, but will also clear the NVRAM. After that, you should be able to boot normally again and apply the update.

Please let us know if you have any trouble during this process. For future reference, opening a [support ticket](https://support.system76.com/) is the most reliable way to get help with your machine.

**Comment by jonahweissman** [comment]
Thanks for the rapid response! These steps solved my problem.

> opening a support ticket is the most reliable way to get help with your machine

Okay, can do. I thought this might be helpful for any other people that might be having the same problem, but I'm happy to ask my questions in whatever channel is most convenient.
